/* tslint:disable */
export const memory: WebAssembly.Memory;
export function __wbindgen_exn_store(a: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function __wbg_state_free(a: number): void;
export function state_new(): number;
export function state_set_year_range(a: number, b: number, c: number): void;
export function state_set_mode(a: number, b: number, c: number): void;
export function state_set_last(a: number, b: number): void;
export function state_add_point(a: number, b: number, c: number): void;
export function state_reset_progress(a: number): void;
export function state_draw_dist(a: number): void;
export function state_set_num_samples(a: number, b: number): void;
export function state_set_pareto(a: number, b: number, c: number): void;
export function state_set_pareto_uniform(a: number, b: number): void;
export function state_set_pareto_beta(a: number, b: number, c: number, d: number): void;
export function state_draw_insights(a: number): void;
export function state_draw_timeline(a: number): void;
